iris dataset use LR, RF, SVM, DT find best ML algorithm using K_Fold_cross_validation

In [39]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
#import numpy as np

In [40]:
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [44]:
LR = cross_val_score(LogisticRegression(), iris.data, iris.target)
LR

C:\Users\kisho\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [49]:
LR.mean()

np.float64(0.9733333333333334)

In [45]:
DTC = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
DTC

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [50]:
DTC.mean()

np.float64(0.9666666666666668)

In [46]:
SVC = cross_val_score(SVC(), iris.data, iris.target)
SVC

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [51]:
SVC.mean()

np.float64(0.9666666666666666)

In [47]:
RFC = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
RFC

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [52]:
RFC.mean()

np.float64(0.9666666666666668)