In [88]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [89]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [90]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\lokes\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [91]:
svc = SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.9851851851851852

In [92]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9796296296296296

In [93]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [94]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [95]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [96]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\lokes\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [97]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9851851851851852

In [98]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9777777777777777

In [99]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [100]:
scores_LR = []
scores_SVM = []
scores_RFC = []

for train_index, test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index], digits.data[test_index], \
                                    digits.target[train_index],digits.target[test_index]
    scores_LR.append(get_score(LogisticRegression(max_iter=250),x_train,x_test,y_train,y_test))
    scores_SVM.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_RFC.append(get_score(RandomForestClassifier(n_estimators=200), x_train, x_test, y_train, y_test))

In [101]:
scores_LR

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [102]:
scores_SVM

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [103]:
scores_RFC

[0.9415692821368948, 0.9649415692821369, 0.9315525876460768]

In [108]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target)


array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [109]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [114]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.93611111, 0.91666667, 0.95264624, 0.94707521, 0.93036212])